// 表单属性【右面板】
export const formConf = {
  formRef: "elForm",
  formModel: "formData",
  size: "medium",
  labelPosition: "right",
  labelWidth: 100,
  formRules: "rules",
  gutter: 15,
  disabled: false,
  span: 24,
};

// 输入型组件【左面板】
export const inputComponents = [
  {
    // 组件的自定义配置
    __config__: {
      label: "单行文本",
      labelWidth: null,
      showLabel: true,
      changeTag: true,
      tag: "el-input",
      tagIcon: "input",
      defaultValue: undefined,
      required: true,
      layout: "colFormItem",
      span: 24,
      document: "https://element.eleme.cn/#/zh-CN/component/input",
    },
    // 组件的插槽属性
    __slot__: {
      prepend: "",
      append: "",
    },
    // 其余的为可直接写在组件标签上的属性
    placeholder: "请输入单行文本",
    style: { width: "100%" },
    clearable: true,
    "prefix-icon": "",
    "suffix-icon": "",
    "show-word-limit": false,
    maxlength: null,
    readonly: false,
    disabled: false,
  },
  {
    __config__: {
      label: "多行文本",
      labelWidth: null,
      showLabel: true,
      changeTag: true,
      tag: "el-input",
      tagIcon: "textarea",
      defaultValue: undefined,
      required: true,
      span: 24,
      document: "https://element.eleme.cn/#/zh-CN/component/input",
    },
    type: "textarea",
    placeholder: "请输入多行文本",
    autosize: {
      minRows: 4,
      maxRows: 4,
    },
    style: { width: "100%" },
    maxlength: null,
    "show-word-limit": false,
    readonly: false,
    disabled: false,
  },
  {
    __config__: {
      label: "密码",
      labelWidth: null,
      showLabel: true,
      changeTag: true,
      tag: "el-input",
      tagIcon: "password",
      defaultValue: undefined,
      required: true,
      span: 24,
      document: "https://element.eleme.cn/#/zh-CN/component/input",
    },
    __slot__: {
      prepend: "",
      append: "",
    },
    type: "password",
    placeholder: "请输入密码",
    style: { width: "100%" },
    "prefix-icon": "",
    "suffix-icon": "",
    "show-word-limit": false,
    maxlength: null,
    readonly: false,
    disabled: false,
  },
  {
    __config__: {
      label: "计数器",
      labelWidth: null,
      showLabel: true,
      changeTag: true,
      tag: "el-input-number",
      tagIcon: "number",
      defaultValue: undefined,
      required: true,
      span: 24,
      document: "https://element.eleme.cn/#/zh-CN/component/input-number",
    },
    placeholder: "计数器",
    min: undefined,
    max: undefined,
    step: 1,
    precision: undefined,
    "controls-position": "",
    "step-strictly": false,
    disabled: false,
  },
  {
    __config__: {
      label: "编辑器",
      showLabel: true,
      changeTag: true,
      labelWidth: null,
      tag: "tinymce",
      tagIcon: "rich-text",
      defaultValue: null,
      span: 24,
      required: true,
      document: "http://tinymce.ax-z.cn",
    },
    placeholder: "请输入",
    height: 300, // 编辑器高度
    branding: false, // 隐藏右下角品牌烙印
  },
];

//选择型组件
export const selectComponents = [
  {
    __config__: {
      label: "下拉选择",
      showLabel: true,
      labelWidth: null,
      changeTag: true,
      tag: "el-select",
      tagIcon: "select",
      span: 24,
      required: true,

      document: "https://element.eleme.cn/#/zh-CN/component/select",
    },
    __slot__: {
      options: [
        {
          label: "选项一",
          value: 1,
        },
        {
          label: "选项二",
          value: 2,
        },
      ],
    },
    placeholder: "请选择下拉选择",
    style: { width: "100%" },
    clearable: true,
    disabled: false,
    filterable: false,
  },
  {
    __config__: {
      label: "级联选择",
      url: "https://www.fastmock.site/mock/f8d7a54fb1e60561e2f720d5a810009d/fg/cascaderList",
      method: "get",
      dataPath: "list",
      dataConsumer: "options",
      showLabel: true,
      labelWidth: null,
      changeTag: true,
      tag: "el-cascader",
      tagIcon: "cascader",
      span: 24,
      required: true,
      defaultValue: [],
      dataType: "dynamic",
      document: "https://element.eleme.cn/#/zh-CN/component/cascader",
    },
    options: [
      {
        id: 1,
        value: 1,
        label: "选项1",
        children: [
          {
            id: 2,
            value: 2,
            label: "选项1-1",
          },
        ],
      },
    ],
    placeholder: "请选择级联选择",
    style: { width: "100%" },
    props: {
      multiple: false,
      checkStrictly: false,
      label: "label",
      value: "value",
      children: "children",
    },
    "show-all-levels": true,
    clearable: true,
    disabled: false,
    separator: "/",
  },
  {
    __config__: {
      label: "单选框组",
      labelWidth: null,
      showLabel: true,
      changeTag: true,
      defaultValue: [],
      tag: "el-radio-group",
      tagIcon: "radio",
      span: 24,
      optionType: "default",
      required: true,
      border: false,
      document: "https://element.eleme.cn/#/zh-CN/component/radio",
    },
    __slot__: {
      options: [
        {
          label: "选项一",
          value: 1,
        },
        {
          label: "选项二",
          value: 2,
        },
      ],
    },

    style: {},
    size: "medium",
    disabled: false,
  },
  {
    __config__: {
      label: "多选框组",
      labelWidth: null,
      showLabel: true,
      changeTag: true,
      optionType: "default",
      tag: "el-checkbox-group",
      tagIcon: "checkbox",
      defaultValue: [],
      span: 24,
      required: true,
      border: false,
      document: "https://element.eleme.cn/#/zh-CN/component/checkbox",
    },
    __slot__: {
      options: [
        {
          label: "选项一",
          value: 1,
        },
        {
          label: "选项二",
          value: 2,
        },
      ],
    },

    style: {},
    size: "medium",
    min: null,
    max: null,
    disabled: false,
  },
  {
    __config__: {
      label: "开关",
      labelWidth: null,
      changeTag: true,
      tag: "el-switch",
      tagIcon: "switch",
      span: 24,
      defaultValue: false,
      showLabel: true,
      required: true,
      document: "https://element.eleme.cn/#/zh-CN/component/switch",
    },
    style: {},
    disabled: false,
    "active-text": "",
    "inactive-text": "",
    "active-color": null,
    "inactive-color": null,
    "active-value": true,
    "inactive-value": false,
  },
  {
    __config__: {
      label: "滑块",
      tag: "el-slider",
      tagIcon: "slider",
      labelWidth: null,
      changeTag: true,
      defaultValue: 0,
      showLabel: true,
      required: true,
      span: 24,
      document: "https://element.eleme.cn/#/zh-CN/component/slider",
    },
    disabled: false,
    min: 0,
    max: 100,
    step: 1,
    "show-stops": false,
    range: false,
  },
  {
    __config__: {
      label: "时间选择",
      labelWidth: null,
      changeTag: true,
      defaultValue: null,
      showLabel: true,
      required: true,
      tag: "el-time-picker",
      tagIcon: "time",
      span: 24,
      document: "https://element.eleme.cn/#/zh-CN/component/time-picker",
    },
    placeholder: "请选择时间选择",
    style: { width: "100%" },
    disabled: false,
    clearable: true,
    "picker-options": {
      selectableRange: "00:00:00-23:59:59",
    },
    format: "HH:mm:ss",
    "value-format": "HH:mm:ss",
  },
  {
    __config__: {
      label: "时间范围",
      labelWidth: null,
      changeTag: true,
      tag: "el-time-picker",
      tagIcon: "time-range",
      span: 24,
      showLabel: true,
      defaultValue: null,
      required: true,
      document: "https://element.eleme.cn/#/zh-CN/component/time-picker",
    },
    style: { width: "100%" },
    "is-range": true,
    disabled: false,
    clearable: true,
    "range-separator": "至",
    "start-placeholder": "开始时间",
    "end-placeholder": "结束时间",
    format: "HH:mm:ss",
    "value-format": "HH:mm:ss",
  },
  {
    __config__: {
      label: "日期选择",
      labelWidth: null,
      changeTag: true,
      tag: "el-date-picker",
      tagIcon: "date",
      span: 24,
      defaultValue: null,
      showLabel: true,
      required: true,
      document: "https://element.eleme.cn/#/zh-CN/component/date-picker",
    },
    placeholder: "请选择日期选择",
    type: "date",
    style: { width: "100%" },
    disabled: false,
    clearable: true,
    format: "yyyy-MM-dd",
    "value-format": "yyyy-MM-dd",
    readonly: false,
  },
  {
    __config__: {
      label: "日期范围",
      labelWidth: null,
      changeTag: true,
      tag: "el-date-picker",
      tagIcon: "date-range",
      span: 24,
      defaultValue: null,
      showLabel: true,
      required: true,
      document: "https://element.eleme.cn/#/zh-CN/component/date-picker",
    },
    style: { width: "100%" },
    type: "daterange",
    "range-separator": "至",
    "start-placeholder": "开始日期",
    "end-placeholder": "结束日期",
    disabled: false,
    clearable: true,
    format: "yyyy-MM-dd",
    "value-format": "yyyy-MM-dd",
    readonly: false,
  },
  {
    __config__: {
      label: "评分",
      labelWidth: null,
      changeTag: true,
      tag: "el-rate",
      tagIcon: "rate",
      span: 24,
      showLabel: true,
      required: true,
      defaultValue: 0,
      document: "https://element.eleme.cn/#/zh-CN/component/rate",
    },
    max: 5,
    "allow-half": false,
    "show-text": false,
    "show-score": false,
    disabled: false,
  },
  {
    __config__: {
      label: "颜色选择",
      labelWidth: null,
      changeTag: true,
      tag: "el-color-picker",
      tagIcon: "color",
      span: 24,
      showLabel: true,
      defaultValue: null,
      required: true,
      document: "https://element.eleme.cn/#/zh-CN/component/color-picker",
    },
    disabled: false,
    size: "medium",
  },
];
